# Generated by Django 2.1.3 on 2018-11-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='ownersofmenu', to='pages.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.ManyToManyField(blank=True, related_name='billuser', to='pages.menu'),
        ),
        migrations.AddField(
            model_name='student',
            name='bill',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='ph_no',
            field=models.CharField(max_length=11),
        ),
    ]
