# Generated by Django 2.1.3 on 2018-11-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181123_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ordered',
            field=models.IntegerField(default=0),
        ),
    ]
