# Generated by Django 2.1 on 2018-11-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_ordercreated_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercreated',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
