# Generated by Django 2.1 on 2018-11-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20181123_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='item_id',
        ),
    ]
