# Generated by Django 2.1 on 2018-11-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20181123_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='amount',
        ),
    ]
