# Generated by Django 2.1 on 2018-11-25 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_student_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercreated',
            name='enter_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
