# Generated by Django 2.1 on 2018-11-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_ordercreated_enter_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='owners',
        ),
    ]
